### ISSUE TITLE
styletags option doesn't always work

### ISSUE THREAD

**Issue by peterbe** [peterbe/minimalcss#266]
I took a random site from hackernews, that doesn't use service workers and does have some `<style>` tags; `http://wiremock.org/`

First I wanted to add a fix because `--styletags` was an available flag but it wasn't sent to the main minimalcss run function. 

```bash
▶ node bin/minimalcss.js -o /tmp/before.css http://wiremock.org/
▶ node bin/minimalcss.js -o /tmp/after.css --styletags http://wiremock.org/
```
But!
```bash
▶ diff /tmp/before.css /tmp/after.css  # Note empty output
```
and 
```bash
▶ ls -l /tmp/before.css /tmp/after.css
-rw-r--r--  1 peterbe  wheel  12612 Sep  7 15:23 /tmp/after.css
-rw-r--r--  1 peterbe  wheel  12612 Sep  7 15:20 /tmp/before.css
```
Same size :(

I can see that the [rendered HTML](view-source:http://wiremock.org/) has this:
```html
<style>.async-hide { opacity: 0 !important} </style>
```
But that string (`.async-hide`) doesn't come into the output CSS.

Can you take a look @jc275 ?

**Comment by jc275** [comment]
Seems like expected behaviour, as the `async-hide` class is unused in the DOM.

There's a script that applies it at some point after page load:
```html
<script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
  h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
  (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
})(window,document.documentElement,'async-hide','dataLayer',4000,
  {'GTM-WQTGSSM':true});</script>
```
I'm not familiar with it, but this _might_ be one of those edge cases where the style is only used transiently between the page-load and network-idle events.
https://github.com/peterbe/minimalcss/blob/a5e8f41f40a33a611e06931cd83e18a01356154c/src/run.js#L298-L299

Likewise, the `fluid-width-video-wrapper` class in the other style tag appears to be unused.

**Comment by jc275** [comment]
Found it: [the "page-hiding snippet"](https://developers.google.com/optimize/devguides/pagehiding)

**Comment by jc275** [comment]
And the `<style>.fluid-width-video-wrapper{...}</style>` element is added after pageload by the [fitvids.js jquery plugin](https://github.com/davatron5000/FitVids.js/blob/master/jquery.fitvids.js). Presumably, it does nothing unless there are embedded videos on the page.

**Comment by peterbe** [comment]
Good sleuthing!
